# Values used for the deployed application.
replicaCount: 2
service:
  name: annotations-rw-neo4j
eksCluster: true
env:
  SHOULD_CONSUME_MESSAGES: true
  SHOULD_FORWARD_MESSAGES: true
  CONSUMER_GROUP: annotations-rw
  CONSUMER_TOPIC: ConceptAnnotations
  PRODUCER_TOPIC: PostConceptAnnotations
  LIFECYCLE_CONFIG_PATH: annotation-config.json
